### ISSUE TITLE
Dropdowns in ListItem not working on touch screens

### ISSUE THREAD

**Issue by ryanmartinneutrino** [qlicker/qlicker#231]
In Chrome, the little drop down menus next to a ListItem (eg to delete a session, etc) don't work. The menu will come up, but it's unclickable, and Chrome doesn't detect the cursor moving over the items in the dropdown. The dropdown is Bootstrap CSS. 

In version  60.0.3112.101 of Chrome, I could fix this by going to chrome://flags and changing "Touch Events API" from "Automatic" to "Disabled". So not sure if this is a Chrome or a Bootstrap issue, so not sure if there is anything that can be done.

In Firefox, it was the same problem. Navigated to about:config, and set dom.w3c._touch_events_enabled to 0 (disabled)

**Comment by ReckoningReckoner** [comment]
I cannot reproduce this. I am going to assume that is was due to the Touch Events API and react. I believe that it [should be resolved](https://github.com/facebook/react/issues/8968). Also, as of [Firefox 52](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events#Browser_compatibility) it has been explicitly fixed.

**Comment by ryanmartinneutrino** [comment]
Just confirmed that it's still an issue in Chrome 64.0.3282.167 on a Surface Book 2

**Comment by ryanmartinneutrino** [comment]
Fixed by PR #508 using the recommendation here:
https://stackoverflow.com/questions/17579750/drop-down-menu-not-working-on-mobile-devices
```
.dropdown-backdrop{
    position: static;
}
```
